// Generated by Wrangler on Tue Apr 23 2024 15:36:57 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	INDEX_SHA256: "f5020a639cf7eccd04d108d055d8e3824b925a3ef72e223040ef09e99c329980";
	MAX_UPLOAD_SIZE_MB: "25";
}
